### ISSUE TITLE
How to create a FCVAR_CHEAT

### ISSUE THREAD

**Issue by ZBzibing** [UeberDaniel/ContagionAngelScript#1]
I need to use the give weapon command
The givewepaon command does not work with slot 5

pPlayer.ConsoleCommand("give kabar");

Can't use cheat command give in multiplayer, unless the server has sv_cheats set to 1.

**Comment by UeberDaniel** [comment]
Hello ZBzibing,
maybe this can be done with a short change of the FCVAR_CHEAT flag of the used command. Unfortunately I'm not that into Contagion AS scripting anymore, so I don't know if this is possible.
Also I am not sure if you can put a weapon in the 5th slot.

You can ask @jonnyboy0719, may he can help you with this.

Greetings.

**Comment by ZBzibing** [comment]
If you use giveweapon(), you will not be able to use giveweapon() if you have phone, slot1 or slot2. So I can only see if I can use the give weapon command

I don't speak English well, so I have to rely on a translator. The AS language is something I have to figure out on my own, as there are no more references on the internet and I can't find a way to do it.

**Comment by jonnyboy0719** [comment]
You should use utilize this instead https://contagion-game.com/api/#cat=Entities&page=CTerrorPlayer&function=GiveWeapon
Though, the entire API is in English.

**pPlayer.GiveWeapon("kabar");**

https://contagion-game.com/api/#cat=Entities&page=CTerrorPlayer contains all the functions and values that you can use to modify **CTerrorPlayer** object.

**Comment by ZBzibing** [comment]
GiveWeapon Does not work in solt3 and solt4
